/**
 * ImportCSV
 *
 * Turn CSV data into resources
 *
 * @category	module
 * @internal	@modx_category Manager and Admin
 * @internal	@properties &dataFile=Data file;string;; &formTpl=Form template chunk;string;;
 * @license 	http://www.gnu.org/copyleft/gpl.html GNU Public License (GPL)
 */
/******************************************
ImportCSV (module)

v1.0 Keith Penton, KP52, December 2012

Create MODX Evo resources from CSV file, preserving templates and TV values 
where names match. CSV file should be full listing from site_content table, 
usually created by module ExportCSV. 
The set of imported fields is selective (see list in ProcessPages fucntion of
import.php for details).

Expects to find CSV files generated by ExportCSV and/or SQL file from 
MySQL database export in import directory. Offers choice of CSV files found in 
assets/import, file named with full path in configuration, or file to be input 
in web form.

NB if using input field, you have to select the radio button next to it as well.

Refresh document tree after import to see results. Imported files will have 
sequential IDs starting from new Root document under site root. IDs in Ditto and 
PubKit parameters are automatically adjusted.

Requires file import.html, or chunk named as formTpl in config, for input form.
Placeholders: [+errors+] (error messages); [+fileChoice+] (radio buttons with
list of importable files/input field); [+tableChoice+] (radio buttons with
list of importable SQL files/input field)

Requires document.class.inc.php

*******************************************/
require $modx->config['base_path'] . 'assets/modules/impex/document.class.inc.php';
require $modx->config['base_path'] . 'assets/modules/impex/import.php';

return $report;
